### ISSUE TITLE
Can we compile ONLY in linux?

### ISSUE THREAD

**Issue by XDM-Inc** [gdaswani/x264_encoder#1]
i use linux primarily and as a beginner im following the guide and its designed for windows but its using linux commands. the NMakefile is for windows and the cmake when you try in linux is throwing error codes. would you mind telling us how to do this entirely  in linux?

**Comment by UDaManFunks** [comment]
I just updated the instructions and fixed the make files, there's a LINUX section in the bottom of the README.md.

Please note that IOPlugins only work in Davinci Resolve Studio (and not on the free version).

**Comment by XDM-Inc** [comment]
ok it compiled flawlessly like clockwork! it compiled a successful "x264_encoder.dvcp" file that i moved to the correct place BUT for some reason my davinci resolve studio 18.6.6 wont find it in the format tab, the old version shows but then i remove it and try the new compiled version it dosent show up as a option anymore either in the quicktime or standalone.
its installed into "/opt/resolve/IOPlugins/x264_encoder.dvcp.bundle/Contents/Linux-x86-64/x264_encoder.dvcp"
here is the compile log, nothing looks off at a glance
[Compile.log](https://github.com/user-attachments/files/16554803/Compile.log)

**Comment by UDaManFunks** [comment]
try doing a git clone of the x264_encoder again and building the binary.    The copying the binary back into the folder "/opt/resolve/IOPlugins/x264_encoder.dvcp.bundle/Contents/Linux-x86-64/"

Note that I changed the way the Codecs are registered in the "Codec" drop down.   There should be four Codecs for X264

X264 Baseline
X264 High
X264 High 4:2:2
X264 Main

![Screenshot 2024-08-08 203336](https://github.com/user-attachments/assets/c013e3c6-4d58-47e9-941a-64450bf59bd4)

MIght want to generate a Davinci Resolve Diagnostic log as well.   My ubuntu box doesn't have a windowing system installed but if you are still having problems, I can check it out early next week to see if I'm able to replicate it (I'd have to install a windowing system on my linux box along with resolve).

**Comment by XDM-Inc** [comment]
recompiled again and this time it shows up but davinci will crash whenever i select ether the mp4 option or the quicktime mp4 options.


the debug log says 

```
/opt/resolve/bin/resolve: symbol lookup error: /opt/resolve/IOPlugins/x264_encoder.dvcp.bundle/Contents/Linux-x86-64/x264_encoder.dvcp: undefined symbol: _ZN8IOPlugin20UISettingsControllerC1ERKNS_21HostCodecConfigCommonE
```
also i forgot to mention i am running Fedora 40 Kde

also tried compiling in different location multiple times and still crashing 

and here is what the log said for yesterday's plugin when it wasnt showing up at all before todays git update

`Plugin Repository :: Plugin library failed to load for /opt/resolve/IOPlugins/x264_encoder.dvcp.bundle/Contents/Linux-x86-64/x264_encoder.dvcp`

**Comment by UDaManFunks** [comment]
I streamlined the instructions one more time for Linux, updated the instructions for compiling x264 (and where to place the binaries), along with changes to x264_encoder Makefile.     You may want to run the entire set of instructions again.

Maybe it'll help.   The undefined symbols sounds like I don't have the right compiler flag / linker flags for LINUX.   I'll have to install Resolve on my Linux box to see if I can get it working.   I'm pretty sure it's not the code itself as it works just fine on Windows albeit the way windows does DLLs vs Linux is totally different.   Was hoping to keep it simple by building the X264 libraries statically to keep the depedencies to a minimum.

**Comment by XDM-Inc** [comment]
same exact error, im going to test 2 things later on today. ill try to install in another distro like ubuntu  and my also a fresh install of my fedora 40 on another drive and see if its just a fedora thing or not.

**Comment by UDaManFunks** [comment]
Sounds good, I just modified the Makefile again to add the linker flag -Wl,-Bsymbolic but not sure if that's actually going to fix the issue.   It supposedly makes it prefer symbols defined in the same shared library to those globally.

**Comment by XDM-Inc** [comment]
yea still crashes

**Comment by UDaManFunks** [comment]
I looked at the error you were getting in your logs, I updated the Makefile one more time.    Pretty sure the reason it was undefined was because I wasn't creating an object file for "uisettings_controller.cpp".

I fixed the Makefile to make sure it gets compiled and an object file gets created.   nm shows "_ZN8IOPlugin20UISettingsControllerC1ERKNS_21HostCodecConfigCommonE" is not undefined anymore in the shared lib (x264_encoder.dvcp)

**Comment by UDaManFunks** [comment]
> yea still crashes

I looked at the error you were getting in your logs, I updated the Makefile one more time. Pretty sure the reason "_ZN8IOPlugin20UISettingsControllerC1ERKNS_21HostCodecConfigCommonE" was undefined was because I wasn't creating an object file for "uisettings_controller.cpp". Forgot to add it to the Makefile for Linux (HEADERS and SRCS properties)

running "nm -D bin/x264_encoder.dvcp | grep _ZN8IOPlugin20UISettingsControllerC1ERKNS_21HostCodecConfigCommonE" is showing it being defined now (previously undefined).

Makefile committed to github.

**Comment by XDM-Inc** [comment]
your last commit did it! works well!

![Screenshot_20240809_190128](https://github.com/user-attachments/assets/461a2734-83fa-40e3-aa64-a3fad6fe3198)

both the standalone mp4 option (without sound) and the quicktime x264 are working! 👍

thanks for your help.

on a side note the old version still crashed on a fresh fedora and i couldn't get davinci setup on ubuntu.( im really bad with ubuntu and dont like it.)

**Comment by UDaManFunks** [comment]
> your last commit did it! works well!

That's running on FEDORA right?  I got Resolve running on UBUNTU 24.04 and compiled the plugin (latest on GITHUB).   It's odd that it's working in FEDORA but not on UBUNTU, the X264 plugins register fine (selectable) but running the export  just basically hangs the program (doesn't really crash).  

I ported the prores_encoder plugin I wrote to Linux, compiled it on UBUNTU and that one exports and works just fine (which is using the more complicated FFMPEG back-end - lol).

**Comment by XDM-Inc** [comment]
So did you fix it for Fedora but it broke for Ubuntu now?

also i see you have a x265 codec as well will that also work on linux or is that a whole another can of worms? (i use Radeon gpu)

**Comment by UDaManFunks** [comment]
I updated the LD_FLAGS and changed the compiler to G++ to make sure those flag are taking effect.   Compiles and exports fine on UBUNTU (24.04)

- https://github.com/UDaManFunks/x264_encoder
- https://github.com/UDaManFunks/x265_encoder
- https://github.com/UDaManFunks/x265_encoder_10b
- https://github.com/UDaManFunks/prores_encoder

I updated the documentation and Makefiles on all four encoders. 

As for your VIDEO CARD, the export CODECs are all software based, and don't rely on the underlying VIDEO card.

X264 encoder uses the X264 LIBRARY
X265 encoder uses the X265 LIBRARY
PRORES encoder uses the FFMPEG LIBRARY

X264 and X265 software encoders are a lot slower than the AVC and HEVC media engines in video cards but they produce consistently better output at lower bit rates.   Specially if the target audience is something like youtube.

**Comment by XDM-Inc** [comment]
Awesome! 👍 I have a Radeon 7900xtx so no HW hardware rendering support on Linux but The much better file sizes are what I'm after because QuickTime is ridiculous turning a 25 megabyte file into a 300 MB file.

**Comment by UDaManFunks** [comment]
> Awesome! 👍 I have a Radeon 7900xtx so I don't "THINK" I have hardware rendering support on Linux or not but The much better file sizes are what I'm after because QuickTime is ridiculous turning a 25 megabyte file into a 300 MB file.

If you are uploading to youtube - be a good idea to take a look at their recommended "encoder settings", specifically the **"bitrate"** section and export your vids based on that table

https://support.google.com/youtube/answer/1722171?hl=en

When I upload to youtube, I use "2-pass" encoding and set the average bit rate to whats listed in that table given resolution and framerate.   Additionally (for youtube), make sure the RES is at least 1440P.

**Comment by XDM-Inc** [comment]
That's what I do now I manually set in the bit right for my FPS and the video contents resolution. But for some reason the stock QuickTime DXHR whatever does not allow you to modify the bitrate (on Linux anyway). That's why I'm so interested in these whole x264 and 265. Here you can select manually the bitrate
